apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blazeserve
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blazeserve
  endpoints:
    - port: http
      path: /__metrics__
      interval: 10s
      scrapeTimeout: 5s
