#!/usr/bin/env bash
# ==============================================================================
# BlazeServe Linux Performance Tuning Script
# Audits and applies kernel network parameters for high-throughput HTTP workloads
# ==============================================================================

set -euo pipefail

MODE="${1:---check}"

SYSCTL_PARAMS=(
    "net.core.somaxconn=65535"
    "net.ipv4.tcp_max_syn_backlog=32768"
    "net.core.netdev_max_backlog=16384"
    "net.ipv4.tcp_fin_timeout=15"
    "net.ipv4.tcp_tw_reuse=1"
    "net.core.rmem_max=16777216"
    "net.core.wmem_max=16777216"
    "fs.file-max=2097152"
    "vm.swappiness=10"
)

echo "⚡ BlazeServe Linux Performance Tuning Tool (Mode: ${MODE})"
echo "=========================================================="

case "${MODE}" in
    --check)
        echo "Auditing current kernel parameters:"
        for item in "${SYSCTL_PARAMS[@]}"; do
            key="${item%%=*}"
            target="${item##*=}"
            current=$(sysctl -n "${key}" 2>/dev/null || echo "N/A")
            printf "  %-35s [Target: %-10s | Current: %s]\n" "${key}" "${target}" "${current}"
        done
        ;;
    --dry-run)
        echo "Dry-run: Parameters that would be written to /etc/sysctl.d/99-blazeserve.conf:"
        for item in "${SYSCTL_PARAMS[@]}"; do
            echo "  ${item}"
        done
        ;;
    --apply)
        if [ "$EUID" -ne 0 ]; then
            echo "Error: --apply requires root privileges (run with sudo)." >&2
            exit 1
        fi
        CONF_FILE="/etc/sysctl.d/99-blazeserve.conf"
        echo "Writing tuning parameters to ${CONF_FILE}..."
        cat << 'EOF' > "${CONF_FILE}"
# Generated by BlazeServe tuning tool
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 32768
net.core.netdev_max_backlog = 16384
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
fs.file-max = 2097152
vm.swappiness = 10
EOF
        sysctl -p "${CONF_FILE}"
        echo "✓ High-throughput network tuning applied successfully!"
        ;;
    *)
        echo "Usage: $0 [--check | --dry-run | --apply]"
        exit 1
        ;;
esac
